# Generated by Django 4.2.3 on 2023-07-28 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_clubtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubtag',
            name='club',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_tags', to='club.club', verbose_name='모임명'),
        ),
    ]
