# Generated by Django 4.2.3 on 2023-07-29 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('club', '0003_alter_clubtag_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('is_owner', models.BooleanField(default=False, verbose_name='모임장 여부')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_club', to='club.club', verbose_name='참여중인 모임')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_user', to=settings.AUTH_USER_MODEL, verbose_name='참여자')),
            ],
            options={
                'verbose_name': 'UserClub',
                'verbose_name_plural': 'UserClubs',
                'db_table': 'user_club',
            },
        ),
    ]
