# Generated by Django 4.2.3 on 2023-08-03 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_alter_userclub_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclub',
            name='nickname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
