# Generated by Django 4.2.3 on 2023-08-07 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_total'),
        ('club', '0006_alter_userclub_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('maximum', models.PositiveIntegerField(blank=True, verbose_name='최대 구매 수량')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club', verbose_name='모임')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='상품')),
            ],
            options={
                'verbose_name': 'ClubProduct',
                'verbose_name_plural': 'ClubProducts',
                'db_table': 'club_product',
            },
        ),
    ]
