# Generated by Django 4.2.3 on 2023-08-08 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_clubproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubproduct',
            name='maximum',
        ),
        migrations.RemoveField(
            model_name='userclub',
            name='nickname',
        ),
    ]
