# Generated by Django 4.2.3 on 2023-08-07 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_clubproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclub',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image', verbose_name='프로필 이미지'),
        ),
    ]
