# Generated by Django 4.2.3 on 2023-08-10 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0010_alter_club_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='achievement',
            field=models.IntegerField(default=0, verbose_name='총 달성률 횟수'),
        ),
    ]
