# Generated by Django 4.2.3 on 2023-08-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_club_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubproduct',
            name='registration',
            field=models.BooleanField(default=False, verbose_name='레벨업 반영 여부'),
        ),
    ]
