# Generated by Django 4.2.3 on 2023-08-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0012_clubproduct_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='achievement',
        ),
        migrations.AddField(
            model_name='club',
            name='achievement_count',
            field=models.IntegerField(default=0, verbose_name='총 달성률 횟수'),
        ),
    ]
