# Generated by Django 4.2.3 on 2023-08-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='represent',
            field=models.CharField(max_length=60, verbose_name='대표자명'),
        ),
    ]
