# Generated by Django 4.2.3 on 2023-08-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_alter_seller_represent'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='business_image',
            field=models.ImageField(blank=True, null=True, upload_to='business_image', verbose_name='판매자 이미지'),
        ),
    ]
