# Generated by Django 4.2.3 on 2023-07-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kakaoId',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='카카오 아이디'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='유저 아이디'),
        ),
    ]
