# Generated by Django 4.2.3 on 2023-08-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='product',
            field=models.CharField(blank=True, null=True),
        ),
    ]
