# Generated by Django 4.2.3 on 2023-08-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('GROUPBUY', 'GROUPBUY'), ('STING', 'STING')], max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='product',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
