# Generated by Django 4.2.3 on 2023-08-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_notification_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='club',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='product',
        ),
        migrations.AddField(
            model_name='notification',
            name='clubproduct',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
