# Generated by Django 4.2.3 on 2023-07-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='상품명')),
                ('intro', models.TextField(blank=True, verbose_name='상품 소개')),
                ('price', models.IntegerField(blank=True, verbose_name='상품 가격')),
                ('category', models.CharField(blank=True, choices=[('FASHION', 'FASHION'), ('DIGITAL', 'DIGITAL'), ('FURNITURE', 'FURNITURE'), ('FOOD', 'FOOD'), ('ANIMAL', 'ANIMAL'), ('SPORTS', 'SPORTS'), ('HOBBY', 'HOBBY'), ('TRAVEL', 'TRAVEL'), ('CROSSBORDER', 'CROSSBORDER'), ('GIFTCARD', 'GIFTCARD'), ('LIFE', 'LIFE')], max_length=255, verbose_name='상품 카테고리')),
                ('seller', models.CharField(blank=True, max_length=255, verbose_name='판매자')),
                ('total', models.IntegerField(blank=True, verbose_name='전체 상품 수량')),
                ('end_at', models.DateTimeField(blank=True, verbose_name='판매 종료 일시')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'product',
            },
        ),
    ]
