# Generated by Django 4.2.3 on 2023-07-28 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_product_thumbnail_product_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('content', models.TextField(blank=True, verbose_name='답변 내용')),
            ],
            options={
                'verbose_name': 'ProductAnswer',
                'verbose_name_plural': 'ProductAnswers',
                'db_table': 'productAnswer',
            },
        ),
        migrations.CreateModel(
            name='ProductQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='질문 제목')),
                ('content', models.TextField(blank=True, verbose_name='질문 내용')),
            ],
            options={
                'verbose_name': 'ProductQuestion',
                'verbose_name_plural': 'ProductQuestions',
                'db_table': 'productQuestion',
            },
        ),
        migrations.CreateModel(
            name='ProductQnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('answer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.productanswer', verbose_name='답변')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='상품')),
                ('question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.productquestion', verbose_name='질문')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='질문한 사람')),
            ],
            options={
                'verbose_name': 'ProductQnA',
                'verbose_name_plural': 'ProductQnA',
                'db_table': 'productQnA',
            },
        ),
    ]
