# Generated by Django 4.2.3 on 2023-07-29 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_productqna_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('gathering', models.BooleanField(default=False, verbose_name='친목/또래모임')),
                ('daily', models.BooleanField(default=False, verbose_name='일상')),
                ('economic', models.BooleanField(default=False, verbose_name='경제')),
                ('biology', models.BooleanField(default=False, verbose_name='동식물')),
                ('culture', models.BooleanField(default=False, verbose_name='문화/예술')),
                ('study', models.BooleanField(default=False, verbose_name='교육/공부')),
                ('life', models.BooleanField(default=False, verbose_name='생활정보')),
                ('sports', models.BooleanField(default=False, verbose_name='스포츠')),
                ('religion', models.BooleanField(default=False, verbose_name='종교')),
                ('health', models.BooleanField(default=False, verbose_name='건강')),
                ('etc', models.BooleanField(default=False, verbose_name='기타')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_tags', to='product.product', verbose_name='모임명')),
            ],
            options={
                'verbose_name': 'ProductTag',
                'verbose_name_plural': 'ProductTags',
                'db_table': 'product_tag',
            },
        ),
    ]
