# Generated by Django 4.2.3 on 2023-07-29 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_producttag_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total',
            field=models.IntegerField(verbose_name='전체 상품 수량'),
        ),
    ]
