# Generated by Django 4.2.3 on 2023-08-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, verbose_name='상품 태그'),
        ),
        migrations.DeleteModel(
            name='ProductTag',
        ),
    ]
