# Generated by Django 4.2.3 on 2023-08-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_tag_delete_producttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.URLField(blank=True, verbose_name='상품 영상'),
        ),
    ]
