# Generated by Django 4.2.3 on 2023-08-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='business_image', verbose_name='상품 썸네일'),
        ),
    ]
