# Generated by Django 4.2.3 on 2023-08-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(blank=True, verbose_name='상품 썸네일'),
        ),
    ]
