# Generated by Django 4.2.3 on 2023-08-13 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0010_product_tag_delete_producttag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('content', models.TextField(blank=True, verbose_name='답변 내용')),
            ],
            options={
                'verbose_name': 'ServiceAnswer',
                'verbose_name_plural': 'ServiceAnswers',
                'db_table': 'ServiceAnswer',
            },
        ),
        migrations.CreateModel(
            name='ServiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='질문 제목')),
                ('content', models.TextField(blank=True, verbose_name='질문 내용')),
            ],
            options={
                'verbose_name': 'ServiceQuestion',
                'verbose_name_plural': 'ServiceQuestions',
                'db_table': 'ServiceQuestion',
            },
        ),
        migrations.CreateModel(
            name='ServiceQnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.productanswer', verbose_name='답변')),
                ('question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.productquestion', verbose_name='질문')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='질문한 사람')),
            ],
            options={
                'verbose_name': 'ServiceQnA',
                'verbose_name_plural': 'ServiceQnA',
                'db_table': 'ServiceQnA',
            },
        ),
    ]
