# Generated by Django 4.2.3 on 2023-07-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='final_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='1개당 최종 가격'),
        ),
        migrations.AlterField(
            model_name='order',
            name='initial_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='1개당 초기 가격'),
        ),
    ]
